#!/usr/bin/env python3
"""
sandwich_runner.py — Assembles the SMPL-X tensor in "sandwich" format:
    stand-still prefix + core (video) + stand-still suffix

Runs inside the GENMO container (where torch is available).
Invoked by run_pipeline_docker.py via:
    docker compose run --rm genmo python scripts/sandwich_runner.py [args]

Arguments:
  --core_pt            Path to hmr4d_results.pt generated by GENMO (core)
  --output_pt          Output path for the combined tensor
  --prefix_frames      Stand-still frames at the start (default: 30)
  --suffix_frames      Stand-still frames at the end   (default: 60)
  --transition_frames  Lerp frames at boundaries       (default: 15)
  --neutral_pose_path  Optional .npy or .pt file with neutral body_pose (63,)
"""

import argparse
from pathlib import Path


NEUTRAL_BODY_POSE_DIM = 63


def _extract_yaw_orient(global_orient_aa):
    """
    Receives a global_orient axis-angle (3,) and returns another axis-angle
    with only the yaw component (rotation around the Y axis) preserved.
    Pitch and roll are zeroed out → robot stays upright facing the same direction as the video.
    """
    import torch
    aa = global_orient_aa.float()
    angle = aa.norm()
    if angle < 1e-6:
        return aa.clone()

    axis = aa / angle
    K = torch.zeros(3, 3)
    K[0, 1], K[0, 2] = -axis[2],  axis[1]
    K[1, 0], K[1, 2] =  axis[2], -axis[0]
    K[2, 0], K[2, 1] = -axis[1],  axis[0]
    R = torch.eye(3) + angle.sin() * K + (1 - angle.cos()) * (K @ K)

    fwd = R[:, 2]
    yaw = torch.atan2(fwd[0], fwd[2])

    c, s = yaw.cos(), yaw.sin()
    Ry = torch.tensor([[c, 0, s], [0, 1, 0], [-s, 0, c]])

    theta = ((Ry.trace() - 1) / 2).clamp(-1, 1).acos()
    if theta.abs() < 1e-6:
        return torch.zeros(3)
    ax = torch.stack([Ry[2,1]-Ry[1,2], Ry[0,2]-Ry[2,0], Ry[1,0]-Ry[0,1]]) / (2 * theta.sin())
    return ax * theta


def _make_standing_body_pose():
    """Creates a (63,) tensor with an upright pose and arms along the body."""
    import torch as _t
    bp = _t.zeros(NEUTRAL_BODY_POSE_DIM)
    bp[36:39] = _t.tensor([0.0,  0.0, -0.4])   # left_collar
    bp[39:42] = _t.tensor([0.0,  0.0,  0.4])   # right_collar
    bp[45:48] = _t.tensor([0.0,  0.0, -0.8])   # left_shoulder
    bp[48:51] = _t.tensor([0.0,  0.0,  0.8])   # right_shoulder
    return bp


def smooth_transitions(combined_pt, t1, t2, n_frames, neutral_body_pose):
    """
    Applies lerp at the sandwich boundaries (same as run_pipeline_refpose.py).

    Prefix [0:t1]  → neutral pose, lerp → core[0]  over the last n_frames
    Suffix [t2:end] → lerp core[-1] → neutral pose over the first n_frames
    """
    import torch

    pred = torch.load(combined_pt, map_location="cpu")
    nbp  = neutral_body_pose

    for section in ("smpl_params_global", "smpl_params_incam"):
        params = pred[section]
        for key in params:
            x   = params[key].float()
            T   = x.shape[0]
            n_suffix = T - t2
            c0  = x[t1].clone()
            cN  = x[t2 - 1].clone()

            if key == "body_pose":
                neutral_pre = nbp.to(x.dtype)
                neutral_suf = nbp.to(x.dtype)
            elif key == "global_orient":
                neutral_pre = _extract_yaw_orient(c0).to(x.dtype)
                neutral_suf = _extract_yaw_orient(cN).to(x.dtype)
            else:
                neutral_pre = neutral_suf = None  # transl, betas

            # Prefix
            if neutral_pre is not None:
                x[:t1] = neutral_pre.unsqueeze(0).expand(t1, *x.shape[1:])
                lerp_start = max(0, t1 - n_frames)
                n_lerp = t1 - lerp_start
                for i in range(n_lerp):
                    w = (i + 1) / (n_lerp + 1)
                    x[lerp_start + i] = neutral_pre * (1.0 - w) + c0 * w
            else:
                x[:t1] = c0.unsqueeze(0).expand(t1, *x.shape[1:])

            # Suffix
            if neutral_suf is not None:
                for i in range(n_suffix):
                    w = min(1.0, (i + 1) / (n_frames + 1))
                    x[t2 + i] = cN * (1.0 - w) + neutral_suf * w
            else:
                x[t2:] = cN.unsqueeze(0).expand(n_suffix, *x.shape[1:])

            params[key] = x
        pred[section] = params

    torch.save(pred, combined_pt)
    print(
        f"[Smooth] Prefix: orient/transl=core[0], neutral body_pose + lerp {n_frames}f | "
        f"Suffix: orient/transl=core[-1], lerp → neutral {n_frames}f"
    )


def main():
    parser = argparse.ArgumentParser(description="Assemble SMPL-X tensor in sandwich format.")
    parser.add_argument("--core_pt",          required=True, help="hmr4d_results.pt from GENMO (core)")
    parser.add_argument("--output_pt",         required=True, help="Output path for the combined tensor")
    parser.add_argument("--prefix_frames",     type=int, default=30,  help="Stand-still frames at the prefix")
    parser.add_argument("--suffix_frames",     type=int, default=60,  help="Stand-still frames at the suffix")
    parser.add_argument("--transition_frames", type=int, default=15,  help="Lerp frames at boundaries")
    parser.add_argument("--neutral_pose_path", default=None,          help="Path to .npy or .pt with neutral body_pose (63,)")
    args = parser.parse_args()

    import torch as _torch
    import numpy as _np

    core_pt    = Path(args.core_pt)
    output_pt  = Path(args.output_pt)

    if not core_pt.exists():
        print(f"[ERROR] core_pt not found: {core_pt}")
        raise SystemExit(1)

    print(f"[Sandwich] Loading core: {core_pt}")
    core = _torch.load(core_pt, map_location="cpu")
    core_frames = core["smpl_params_global"]["transl"].shape[0]

    prefix_frames = args.prefix_frames
    suffix_frames = args.suffix_frames

    print(f"[Sandwich] Prefix: {prefix_frames} frames | Core: {core_frames} frames | Suffix: {suffix_frames} frames")

    # Assemble combined tensor (core boundaries as placeholder — smooth_transitions overwrites)
    combined = {}
    for section in ("smpl_params_global", "smpl_params_incam"):
        combined[section] = {}
        for key, c in core[section].items():
            prefix = c[0:1].expand(prefix_frames, *c.shape[1:]).clone()
            suffix = c[-1:].expand(suffix_frames, *c.shape[1:]).clone()
            combined[section][key] = _torch.cat([prefix, c, suffix], dim=0)

    K = core.get("K_fullimg")
    if K is not None and K.ndim == 3 and K.shape[1:] == (3, 3):
        combined["K_fullimg"] = _torch.cat([
            K[0:1].expand(prefix_frames, 3, 3).clone(),
            K,
            K[-1:].expand(suffix_frames, 3, 3).clone(),
        ], dim=0)
    else:
        T_total = prefix_frames + core_frames + suffix_frames
        combined["K_fullimg"] = _torch.eye(3).unsqueeze(0).expand(T_total, 3, 3).clone()

    output_pt.parent.mkdir(parents=True, exist_ok=True)
    _torch.save(combined, output_pt)
    total = prefix_frames + core_frames + suffix_frames
    print(f"[Sandwich] Combined tensor saved: {total} frames → {output_pt}")

    # Neutral pose
    if args.neutral_pose_path:
        p = Path(args.neutral_pose_path)
        neutral_body_pose = (
            _torch.from_numpy(_np.load(p)).float()
            if p.suffix == ".npy"
            else _torch.load(p, map_location="cpu").float()
        )
        neutral_body_pose = neutral_body_pose.reshape(NEUTRAL_BODY_POSE_DIM)
    else:
        neutral_body_pose = _make_standing_body_pose()

    smooth_transitions(
        output_pt,
        t1=prefix_frames,
        t2=prefix_frames + core_frames,
        n_frames=args.transition_frames,
        neutral_body_pose=neutral_body_pose,
    )

    print(f"[Sandwich] Done: {output_pt}")


if __name__ == "__main__":
    main()
